FROM node:22-alpine
WORKDIR /app

# Кэшируем установку зависимостей
COPY package*.json ./
RUN npm install

COPY . .
EXPOSE 3000

# Запускаем dev-сервер с привязкой ко всем интерфейсам
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]